### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by leifdenby** [mllam/weather-model-graphs#1]
*v0.1.0*
- graph creation
    - graph archetypes
        - [ ] Keisler nearest-neighbour
        - [ ] GraphCast multi-range
        - [ ] Oscarsson hierarchical
- graph visualisation
    - [ ] 2D using matplotlib+networkx with node and edge rendering with arched directed edges and colouring of edges and nodes by attribute value
- graph splitting
    - [ ] split graph by attribute value
- saving graphs
    - [ ] pytorch-geometric format for neural-lam (uses torch.pickle and specific splitting of graph and filename format)
    - [ ] pickle of `networkx.DiGraph` objects
- readme
   - [ ] install instructions, detailing optional dependency on pytorch and pytorch geometric
   - [ ] background on graph-based weather models and design of package
   - [ ] package module overview

TODO
- [ ] fix typo `architype` to `archetype`
- [ ] add docstrings to archetype creation functions
- [ ] rename `weather_model_graphs.visualise.nx_draw_with_pos_and_attr(...)` with `weather_model_graphs.visualise.draw_2d(...)`, double check doc string
- [ ] add install instructions, remove pytorch from deps and explain how to install for gpu or cpu if needed
- [ ] add `g2m`, `m2m`, `m2g` visualisation to README

*v0.2.0*
- [ ] add optional support for faster graph backend, for example [graph-tool](https://graph-tool.skewed.de/) with underlying routines written in c++. Should wrap graph-tool digraph representation in new class `wmg.graphtool.WrappedDiGraph` which behaves like a `networkx.DiGraph` for the operations we need
- [ ] add 3D visualisation using the Plotly based routines in https://github.com/joeloskarsson/neural-lam/blob/main/plot_graph.py

**Comment by leifdenby** [comment]
@joeloskarsson I am happy to revisit this roadmap to create a new release with just the PRs you have been working on. Maybe you could see if you would like to have a tagged release at some point and let me know? I can always push the functionality I mention above to later version numbers. I only made the roadmap to give an idea of features I would like to add and in what order

**Comment by joeloskarsson** [comment]
Yes it would probably be good to have the things I am working on / planning to work on in here. I don't have any strong opinions about the ordering of these things, or creating specific releases, so I'll let you plan that out. But I'll list here the things I have been doing and are planning to do, so you can add them to the roadmap:

## Done / on the way

* #19 (merged)
* #21 (PR)

# Planned (roughly in this order)

* Create "better" strategy for m2g-connection than 4-nearest-neighbors, that is close to GraphCast strategy but for a quadrilateral LAM mesh graph. Specifically, find the "square" in the mesh containing the grid node and connect it to the four corner mesh nodes. Connect grid nodes outside the mesh bounding box only to the two closest neighbors.
* (already on the roadmap) _Remove the assumption that the input grid is regular_
* Triangular mesh graphs, by similar type of refinement as in GraphCast.

Maybe @TomasLandelius would want to also add an entry about the SOM-based graph creation discussed here: https://github.com/mllam/neural-lam/issues/4#issuecomment-2141308373

**Comment by joeloskarsson** [comment]
In the developer calls it had been decided to switch from these roadmap issues to using the github milestones. Please see https://github.com/mllam/weather-model-graphs/milestones for the up to date roadmap.
